services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.0 # 
    container_name: mealie
    restart: unless-stopped
    #ports:
    #  - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # mealie devs recommend setting a max mem level
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: http://mealie.localdomain.lan
      # Database Settings
      DB_ENGINE: postgres
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    #networks:
    #  - mealie

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - ./mealie-pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    #networks:
    #  - mealie

networks:
  default:
    external: true
    name: mealie
